name: Sync to Client Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync to client repo
      env:
        CLIENT1_PAT: ${{ secrets.CLIENT1_PAT }}
      run: |
        git config --global user.name "sharplemon23"
        git config --global user.email "miguelcolmenareswebdev@gmail.com"
        git remote add client https://sochperformance:${CLIENT1_PAT}@github.com/sochperformance/next14.git
        git push client main --force
