name: Sync Client Repository

on:
  push:
    branches:
      - main

jobs:
  sync-client:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Configure Git user with your agency's credentials
      - name: Set up Git user
        run: |
          git config --global user.email "miguelcolmenareswebdev@gmail.com"
          git config --global user.name "sharplemon23"

      # Step 3: Sync changes to the client repository
      - name: Sync to Client Repo
        env:
          CLIENT_PAT: ${{ secrets.CLIENT_PAT }}
        run: |
          git remote add client https://sochperformance:${{ secrets.CLIENT_PAT }}@github.com/sochperformance/test-web-one.git
          git push client main --force
