name: Sync Client Repository

on:
  push:
    branches:
      - main

jobs:
  sync-client:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

    

      # Step 3: Sync changes to the client repository
      - name: Sync to Client Repo
        env:
          CLIENT_PAT: ${{ secrets.CLIENT1_PAT }}
        run: |
          git remote add client https://sochperformance:${{ secrets.CLIENT1_PAT }}@github.com/sochperformance/test-web.git
          if [ -z "$(git ls-remote client)" ]; then
            echo "Repository is empty. Initializing..."
            git checkout --orphan temp
            git commit --allow-empty -m "Initial commit"
            git push client temp:main
            git branch -D temp
          else
            git push client main --force
