name: Update Client Repository

on:
  push:
    branches:
      - main  # Adjust if your main branch is named differently

jobs:
  update-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "bot@noreply.github.com"
          git config --global user.name "Git bot"

      - name: Push to Client's Repository
        run: |
          git remote add client https://github.com/sochperformance/test-web.git
          git push client HEAD:main
        env:
          PAT: ${{ secrets.CLIENT1_PAT }}
