name: Update Client Repository

on:
  push:
    branches:
      - main

jobs:
  update-client:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Initialize repository if empty
      - name: Initialize if empty
        run: |
          if [ -z "$(git ls-remote client)" ]; then
            echo "Repository is empty. Initializing..."
            git commit --allow-empty -m "Initial commit"
          fi

      # Step 3: Sync changes to the client repository
      - name: Sync to Client Repo
        env:
          CLIENT1_PAT: ${{ secrets.CLIENT1_PAT }}
        run: |
          git remote add client https://sochperformance:${{ secrets.CLIENT1_PAT }}@github.com/sochperformance/test-web.git
          git push client main --force
