name: Sync to Client Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Ensure initial commit
        run: |
          if [ "$(git rev-parse --is-inside-work-tree)" != "true" ]; then
            git init
            echo "# Initial Commit" > README.md
            git add README.md
            git commit -m "Initial commit"
          fi
      
      - name: Sync with Client Repository
        if: success()
        env:
          CLIENT_PATH: ${{ secrets.CLIENT_PATH }}
        run: |
          git remote add client https://sochperformance:${CLIENT_PATH}@github.com/sochperformance/web-testing.git
          git push client main --force
