name: Update Client Repository

on:
  push:
    branches:
      - main

jobs:
  update-client:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Git configuration
      - name: Configure Git
        run: |
          git config --global user.email "miguelcolmenareswebdev@gmail.com"
          git config --global user.name "sharplemon23"

      # Step 3: Add the client remote
            - name: Add Client Remote
        env:
          CLIENT1_PAT: ${{ secrets.CLIENT1_PAT }}
        run: |
          git remote add client https://sharplemon23:${{ secrets.CLIENT1_PAT }}@github.com/sochperformance/test-web.git



      # Step 4: Initialize repository if empty and push
      - name: Sync to Client Repo
        env:
          CLIENT1_PAT: ${{ secrets.CLIENT1_PAT }}
        run: |
          if [ -z "$(git ls-remote client)" ]; then
            echo "Repository is empty. Initializing..."
            git commit --allow-empty -m "Initial commit"
          fi
          git push client main --force







