- name: Sync to client repo
  env:
    CLIENT1_PAT: ${{ secrets.CLIENT1_PAT }}
  run: |
    git config --global user.name "sochperformance"
    git config --global user.email "sochperformance@gmail.com"
    git remote add client https://github.com/sochperformance/test-web.git
    git push client main --force
