name: Sync to Client Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mirror repository to client
        env:
          CLIENT_PAT: ${{ secrets.CLIENT1_PAT }}
        run: |
          git remote add client https://sochperformance:${{ secrets.CLIENT1_PAT }}@github.com/sochperformance/test-web.git
          git push client main --force
