name: Sync to Client Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Sync with Client  Repository
        if: success()
        env:
          CLIENT_PAT: ${{ secrets.CLIENT_PAT }}
        run: |
          git remote add client1 https://sharplemon23:${CLIENT_PAT}@github.com/sochperformance/test-web.git
          git push client1 main --force

     