name: Sync to Client Repo

on:
  push:
    branches:
      - main

jobs:
  job-name:
    permissions:
      contents: write
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check repository URL
        run: |
          echo "Repository URL: https://sochperformance:${{ secrets.CLIENT1_PAT }}@github.com/sochperformance/test-web.git"
          git remote add client https://sochperformance:${{ secrets.CLIENT1_PAT }}@github.com/sochperformance/test-web.git
          git remote -v
          git push client main --force
